#!/usr/bin/env python3
"""
Phase 6 (Stage 1) - Learned Re-ranker (LightGBM).

Goal:
  Take the up to 200 candidates per S1 generated by Phase 5 Blocking.
  Train a fast Stage-1 ranker (using LightGBM) on the pre-computed cosines + priority.
  Trim down to the top-N (e.g., N=30) candidates per S1 to feed into the expensive Stage-2 feature generator.

Steps:
  1. Load ground truth.
  2. Load train and val candidate shards from `data_cand/train_s400000` and `data_cand/val_full`.
  3. Feature engineering:
     - Extract individual pass bits from the `passes` bitmask.
     - Add per-S1 context features (gap to best priority, count of strong candidates).
  4. Downsample negatives in train (keep all positives, keep top hard negatives + random negatives).
  5. Train LightGBM Ranker.
  6. Evaluate oracle F0.5 on val at various top-N cutoffs.
  7. Save the trained model for inference.

Usage:
  python src/phase6_stage1.py --train-cand data_cand/train_s400000 --val-cand data_cand/val_full
"""

import argparse
import glob
import json
import os
import time
from pathlib import Path

import lightgbm as lgb
import numpy as np
import pandas as pd

import blocking as B
from common import read_table

T0 = time.time()

def log(msg):
    print(f"[{time.time() - T0:7.0f}s] {msg}", flush=True)

def f05(r):
    return 1.25 * r / (0.25 + r) if r > 0 else 0.0

def load_ground_truth(path: Path) -> dict:
    """Returns dict of s1_id -> set of true cand_ids."""
    gt = pd.read_csv(path, sep="\t", dtype=str, keep_default_na=False)
    truth = {}
    for r in gt.itertuples(index=False):
        truth.setdefault(r.s1_id, set()).add(r.matched_id)
    return truth

def load_candidates(cand_dir: Path, truth: dict = None) -> pd.DataFrame:
    """Loads all parquet shards from cand_dir, optionally labels them with GT."""
    shards = glob.glob(str(cand_dir / "*.parquet"))
    if not shards:
        raise FileNotFoundError(f"No .parquet files found in {cand_dir}")
    
    log(f"Loading {len(shards)} shards from {cand_dir.name}...")
    dfs = []
    for s in shards:
        df = pd.read_parquet(s)
        # Keep only required columns to save memory
        cols = ["s1_id", "cand_id", "passes", "priority", "rank"] + B.COS_COLS
        dfs.append(df[cols])
    df = pd.concat(dfs, ignore_index=True)
    
    if truth is not None:
        log("Applying ground truth labels...")
        # Vectorized labelling: check if cand_id is in truth[s1_id]
        # (This can be slow if done row-by-row; we use map/apply carefully)
        def is_match(row):
            return 1 if row.cand_id in truth.get(row.s1_id, set()) else 0
        
        # A faster way for huge dfs:
        # Create a set of true tuples (s1, cand)
        true_pairs = {(s1, c) for s1, cands in truth.items() for c in cands}
        # Check membership
        df["label"] = [1 if (s1, c) in true_pairs else 0 for s1, c in zip(df["s1_id"], df["cand_id"])]
        log(f"Found {df['label'].sum():,} positives out of {len(df):,} candidates")
        
    return df

def feature_engineering(df: pd.DataFrame) -> pd.DataFrame:
    """Extracts features from existing blocking output."""
    log("Engineering Stage-1 features...")
    # 1. Unpack pass bits (there are 13 passes in B.PASS_BIT)
    for p, bit in B.PASS_BIT.items():
        df[f"pass_{p}"] = (df["passes"] & bit) > 0

    # 2. Per-S1 context features
    # Group by s1_id to find max priority per S1
    grouped = df.groupby("s1_id")["priority"]
    best_priority = grouped.transform("max")
    
    df["gap_to_best"] = best_priority - df["priority"]
    df["priority_ratio"] = df["priority"] / (best_priority + 1e-6)
    
    # 3. Fill NA for cosines just in case
    for c in B.COS_COLS:
        df[c] = df[c].fillna(0.0)
        
    # Sort by s1_id and rank (LGBMRanker requires grouped contiguous data)
    df = df.sort_values(["s1_id", "rank"]).reset_index(drop=True)
    return df

def downsample_train(df: pd.DataFrame, hard_n: int = 15, random_n: int = 5, seed: int = 42) -> pd.DataFrame:
    """
    Keeps all positives.
    Keeps top `hard_n` negatives per S1.
    Keeps `random_n` random remaining negatives per S1.
    """
    log("Downsampling train negatives...")
    np.random.seed(seed)
    
    pos = df[df["label"] == 1]
    neg = df[df["label"] == 0]
    
    # Top N hard negatives (rank is already 0 to 199 from blocking)
    hard_neg = neg[neg["rank"] < hard_n]
    
    # Random negatives (sample from the rest)
    rest_neg = neg[neg["rank"] >= hard_n]
    # To sample random_n per group efficiently:
    rest_neg = rest_neg.sample(frac=1.0, random_state=seed) # shuffle
    random_neg = rest_neg.groupby("s1_id").head(random_n)
    
    sampled = pd.concat([pos, hard_neg, random_neg], ignore_index=True)
    sampled = sampled.sort_values(["s1_id", "rank"]).reset_index(drop=True)
    log(f"Downsampled train from {len(df):,} to {len(sampled):,} rows")
    return sampled

def evaluate_oracle_at_n(df: pd.DataFrame, preds: np.ndarray, budgets: list) -> dict:
    """Evaluates the Oracle F0.5 if we take the top N predicted candidates per S1."""
    df = df.copy()
    df["pred"] = preds
    
    # Rank candidates per S1 based on prediction (descending)
    df["pred_rank"] = df.groupby("s1_id")["pred"].rank(method="first", ascending=False)
    
    # Total S1 entities in val
    s1_count = df["s1_id"].nunique()
    
    res = {}
    for b in budgets:
        # Filter to top b candidates
        kept = df[df["pred_rank"] <= b]
        
        # Calculate recall metrics
        found = kept.groupby("s1_id")["label"].sum()
        total_true = df.groupby("s1_id")["label"].sum()
        
        # Recall per S1
        r = (found / total_true).fillna(-1) # -1 for singletons (0 true matches)
        f_scores = np.where(r < 0, 1.0, np.vectorize(f05)(np.clip(r, 0, 1)))
        
        # Pair recall overall
        pair_recall = found.sum() / total_true.sum() if total_true.sum() > 0 else 0
        
        res[str(b)] = {
            "pair_recall": round(pair_recall, 5),
            "oracle_macro_f05": round(float(f_scores.mean()), 5),
            "s1_all_matches_found": round(float((r[r >= 0] == 1).mean()), 5)
        }
    return res

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--train-cand", default="data_cand/train_s400000")
    ap.add_argument("--val-cand", default="data_cand/val_full")
    ap.add_argument("--phase0-dir", default="artifacts/phase0")
    ap.add_argument("--out-dir", default="artifacts/phase6")
    ap.add_argument("--downsample-hard", type=int, default=15)
    ap.add_argument("--downsample-rand", type=int, default=5)
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    
    # 1. Load GT
    gt_path = Path(args.phase0_dir) / "gt_long.tsv"
    log(f"Loading ground truth from {gt_path}...")
    truth = load_ground_truth(gt_path)
    
    # 2. Load Train
    df_train = load_candidates(Path(args.train_cand), truth)
    df_train = feature_engineering(df_train)
    df_train = downsample_train(df_train, args.downsample_hard, args.downsample_rand)
    
    # 3. Load Val
    df_val = load_candidates(Path(args.val_cand), truth)
    df_val = feature_engineering(df_val)
    
    # 4. Prepare datasets for LightGBM
    features = [
        "priority", "rank", "gap_to_best", "priority_ratio"
    ] + B.COS_COLS + [f"pass_{p}" for p in B.PASS_BIT.keys()]
    
    X_train = df_train[features]
    y_train = df_train["label"]
    group_train = df_train.groupby("s1_id").size().to_numpy()
    
    X_val = df_val[features]
    y_val = df_val["label"]
    group_val = df_val.groupby("s1_id").size().to_numpy()
    
    log(f"Features ({len(features)}): {features}")
    
    # 5. Train LightGBM Ranker
    log("Training LightGBM Ranker (lambdarank)...")
    ranker = lgb.LGBMRanker(
        objective="lambdarank",
        metric="ndcg",
        boosting_type="gbdt",
        learning_rate=0.1,
        num_leaves=31,
        n_estimators=500,
        random_state=42,
        importance_type="gain"
    )
    
    ranker.fit(
        X_train, y_train, group=group_train,
        eval_set=[(X_val, y_val)], eval_group=[group_val],
        eval_at=[10, 30],
        callbacks=[lgb.early_stopping(stopping_rounds=30), lgb.log_evaluation(period=50)]
    )
    
    # 6. Evaluate Oracle F0.5 at different N
    log("Predicting on Validation set...")
    val_preds = ranker.predict(X_val)
    
    budgets = [10, 15, 20, 30, 50]
    results = evaluate_oracle_at_n(df_val, val_preds, budgets)
    
    log("\n### Oracle F0.5 on Val by Top-N Cutoff ###")
    for b, metrics in results.items():
        log(f"Top {b}: Oracle F0.5 = {metrics['oracle_macro_f05']:.5f} | Recall = {metrics['pair_recall']:.5f}")
        
    # Check if we hit the target
    target_met = False
    best_n = 50
    for b in budgets:
        if results[str(b)]["oracle_macro_f05"] >= 0.995:
            target_met = True
            best_n = b
            log(f"🎯 Target Oracle F0.5 >= 0.995 MET at Top-{b}!")
            break
            
    if not target_met:
        log("⚠️ Target Oracle F0.5 of 0.995 was not met even at Top-50.")
    
    report = {
        "args": vars(args),
        "features": features,
        "results": results,
        "best_n": best_n,
        "feature_importances": {f: float(imp) for f, imp in zip(features, ranker.feature_importances_)}
    }
    
    with open(out_dir / "stage1_report.json", "w") as f:
        json.dump(report, f, indent=1)
        
    model_path = out_dir / "stage1_ranker.txt"
    ranker.booster_.save_model(model_path)
    log(f"Saved model to {model_path}")
    log("Done!")

if __name__ == "__main__":
    main()
